### ISSUE TITLE
Addition to fnv1a_xor_hashes.txt

### ISSUE THREAD

**Issue by cybercdh** [fireeye/sunburst_countermeasures#11]
msmpeng : 5183687599225757871

aka Microsoft Security Essentials

**Comment by cybercdh** [comment]
10374841591685794123 : win64_remotex64

which i think is to do with IDA Pro ..?

**Comment by cybercdh** [comment]
640589622539783622 : xagtnotif
10063651499895178962 : mssense

**Comment by jhsmith** [comment]
Thanks! Added in #19
