### ISSUE TITLE
Addition to fnv1a_xor_hashes.txt

### ISSUE THREAD

**Issue by Recurzion** [fireeye/sunburst_countermeasures#14]
11266044540366291518 : connection
6116246686670134098 : content-type
9007106680104765185 : referer
5449730069165757263 : blacklight
506634811745884560 : reflector

Thanks to @cybercdh for the tooling.

**Comment by cybercdh** [comment]
nice find!

**Comment by jhsmith** [comment]
Thanks! Added in #19
